export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_USER_PREFERRED_ENTITY = 'SET_USER_PREFERRED_ENTITY';
export const LOGOUT = 'LOGOUT';
export const SET_DEFAULT_TIMETABLE = 'SET_DEFAULT_TIMETABLE';
export const SET_TIMETABLE_LOADED = 'SET_TIMETABLE_LOADED';
export const SET_PATCHES = 'SET_PATCHES';
